### PR TITLE
Added a disco twist to the story, including ascii art

### PR DESCRIPTION
**Pull request by floridop**
Added some changes to your story. You are free to ask me to do any change you like before approving!

### CODE REVIEW

**Review by fredholmP — CHANGES_REQUESTED** [review]
There seems to be some weird letters 'gpyy' on line 33 that do not belong to the ASCII art. Please remove these.

**Comment by floridop** [comment]
Hi @fredholmP 
I would prefer not to remove these, or if I do it should be mentioned in the document, as these characters happens to be the artist's tag as present in the referenced source so it's nice to keep it there to give credit.

**Review by fredholmP — APPROVED** [review]
The additional lines were given proper justification.

**Comment by floridop** [comment]
I'll close this part of the homework, but if there is something else 
you're curious to try and I am available I'll be happy to test.

**Pull request merged**
